# Generated by Django 4.0.5 on 2022-06-12 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProd',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria Proucto')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codProducto', models.IntegerField(max_length=50, primary_key=True, serialize=False, verbose_name='Codigo Producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre producto')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripccion Producto')),
                ('stock', models.IntegerField(max_length=3, verbose_name='Cantidad Disponible')),
                ('precio', models.IntegerField(max_length=10, verbose_name='Precio Producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriaprod')),
            ],
        ),
    ]
