# Generated by Django 4.0.5 on 2022-06-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codProducto',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(verbose_name='Precio Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(verbose_name='Cantidad Disponible'),
        ),
    ]
