# Generated by Django 4.0.5 on 2022-06-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_codproducto_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codProducto',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Codigo Producto'),
        ),
    ]
