# Generated by Django 4.0.5 on 2022-06-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_producto_imagen_alter_producto_codproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fotoProd',
            field=models.ImageField(null=True, upload_to='static/img/'),
        ),
    ]
