# Generated by Django 4.0.5 on 2022-06-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_producto_fotoprod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('idFundacion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Fundacion')),
                ('nombreFundacion', models.CharField(max_length=50, verbose_name='Nombre Fundacion')),
                ('direccionFundacion', models.CharField(max_length=50, verbose_name='Direccion Fundacion')),
                ('emailFundacion', models.CharField(max_length=50, verbose_name='Email Fundacion')),
                ('telefonoFundacion', models.CharField(max_length=10, verbose_name='Telefono Fundacion')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fotoProd',
        ),
    ]
