# Generated by Django 4.0.5 on 2022-06-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fundacion_remove_producto_fotoprod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fundacion',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenProd',
            field=models.ImageField(null=True, upload_to='static/img/'),
        ),
    ]
