# Generated by Django 4.0.4 on 2022-06-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_producto_imagenprod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('codFormu', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Formulario')),
                ('nombreF', models.CharField(max_length=50, verbose_name='Nombre ')),
                ('apellidoF', models.CharField(max_length=50, verbose_name='Apellido')),
                ('mailF', models.EmailField(max_length=254)),
                ('phoneF', models.IntegerField(verbose_name='Teléfono')),
                ('direccionF', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección')),
                ('regionF', models.IntegerField(choices=[[1, 'Región Metropolitana'], [2, 'I Tarapacá'], [3, 'II Antofagasta'], [4, 'III Atacama'], [5, 'IV Coquimbo'], [6, 'V Valparaíso'], [7, 'VI Lib. Gral. Bernardo O Higgins'], [8, 'VII Maule'], [9, 'VIII Bío-Bío'], [10, 'IX Araucanía'], [11, 'X De Los Lagos'], [12, 'XI Aysén'], [13, 'XII Magallanes Y Antártica'], [14, 'XIV De Los Ríos'], [15, 'XV Arica y Parinacota']])),
                ('comunaF', models.CharField(max_length=250, verbose_name='Comuna')),
            ],
        ),
        migrations.AlterField(
            model_name='categoriaprod',
            name='idCategoria',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Categoria Proucto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codProducto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenProd',
            field=models.ImageField(null=True, upload_to='media/img/'),
        ),
    ]
