# Generated by Django 4.0.5 on 2022-06-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_contacto_regionf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('codFundacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Fundacion')),
                ('nomFundacion', models.CharField(max_length=50, verbose_name='Nombre Fundacion')),
                ('descFundacion', models.CharField(max_length=200, verbose_name='Descripcion Fundacion')),
                ('dirFundacion', models.CharField(max_length=50, verbose_name='Direccion Fundacion')),
                ('telFundacion', models.IntegerField(verbose_name='Telefono Contacto')),
                ('mailFundacion', models.EmailField(max_length=254, verbose_name='Correo')),
                ('imgFundacion', models.ImageField(null=True, upload_to='media/img/')),
            ],
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mailF',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='regionF',
            field=models.CharField(max_length=250, verbose_name='Región de Cliente'),
        ),
    ]
