# Generated by Django 4.0.5 on 2022-07-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_fundacion_imgfundacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codUser', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Usuario')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Persona')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido Persona')),
                ('mailUser', models.EmailField(max_length=254, verbose_name='Mail Persona')),
                ('telefono', models.IntegerField(verbose_name='Telefono User')),
                ('nombreUser', models.CharField(max_length=50, verbose_name='Nombre de Usuario')),
                ('passUser', models.CharField(max_length=50, verbose_name='Contraseña Usuario')),
            ],
        ),
    ]
