# Generated by Django 4.0.5 on 2022-07-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido '),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='mailUser',
            field=models.EmailField(max_length=254, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
